worker:
  build: .
  dockerfile: Dockerfile.worker
  hostname: worker
  environment:
    MAX_CPU_CORES: 2
  links:
   - server

server:
  build: .
  dockerfile: Dockerfile.server
  hostname: server
  ports:
   - "5672:5672" # RabbitMQ
   - "6379:6379" # Redis
  environment:
    MAX_CPU_CORES: 2
    PENDULUM_RESOLUTION: 36
  volumes:
   - /tmp/results:/results
